[package]
name = "client"
version = "0.1.0"
authors = ["Hossein Daneshvar <daneshvar.ho@gmail.com>"]
edition = "2018"

[[bin]]
name = "client"
path = "src/bin/main.rs"

[dependencies]
tokio = { version = "0.2", features = ["full"] }
elapsed = "0.1"
bytesize = "1.0.0"
