version: '3.4'

services:
  server:
    image: downup:latest
    command: server
    build:
      context: .
    volumes:
      - type: bind
        source: ./server.toml
        target: /etc/config.toml
        read_only: true

  client:
    image: downup:latest
    command: client
    build:
      context: .
    volumes:
      - type: bind
        source: ./client.toml
        target: /etc/config.toml
        read_only: true
