version: '3.4'

services:
  server:
    image: server:latest
    build:
      context: ./server

  client:
    image: client/latest
    build:
      context: ./client
    volumes:
      - type: bind
        source: ./client.toml
        target: /etc/config.toml
        read_only: true
